### ISSUE TITLE
new eslint rules

### ISSUE THREAD

**Issue by TkDodo** [pmedianetwork/eslint-config#15]
---

PR: #18

---

This issue is about new eslint rules and stuff we want to remove/change

- [x] move snippet below
- [x] react/prop-types for typescript files #16
- [x] remove jsx-a11y/anchor-is-valid #10
- [x] add exceptions for x, y, and z for rule id-length #17 
- [x] test all 4 rules in insights and datatap (react/prop-types only in datatap)

```
    "overrides": [
        {
            "files": ["**/*.test.js"],
            "env": {
                "jest": true
            },
            "rules": {
                "max-len": "off",
                "no-unused-expressions": "off",
                "no-useless-computed-key": "off", // flow does not support non-string property keys https://github.com/facebook/flow/issues/380
                "react/no-find-dom-node": "off"
            }
        }
    ]
```

**Comment by namjul** [comment]
duplicate of https://github.com/pmedianetwork/eslint-config/issues/1

**Comment by georggrubner** [comment]
react/prop-types does not trigger false positive for me. lets discuss that on monday @TkDodo
