### ISSUE TITLE
Create custom eslint rule

### ISSUE THREAD

**Issue by adamgajzlerowicz** [pmedianetwork/eslint-config#65]
@adamgajzlerowicz commented on [Tue Mar 03 2020](https://github.com/pmedianetwork/adverity-presense-frontend/issues/327)

PR https://github.com/pmedianetwork/eslint-config/pull/64

---

**About**
We require an implementation of a custom eslint rule. 
This rule will almost a fork of [no-relative-parent-imports](https://github.com/benmosher/eslint-plugin-import/blob/master/src/rules/no-relative-parent-imports.js), with a difference that it will allow importing from one level up.

---

**Tasks**

- [x] lint rule is implemented in our own repository
- [x] rule is added do eslint repository as a warning for now
- [ ] ~warnings are fixed within presence repository~

---

@adamgajzlerowicz commented on [Wed Mar 04 2020](https://github.com/pmedianetwork/adverity-presense-frontend/issues/327#issuecomment-594459367)

Here is the plugin code:
https://github.com/adamgajzlerowicz/sensible-imports

For a prototype I used my own repo, but once we decide we are going to use it I will move it to company namespace.

Here is plugin test result
![image](https://user-images.githubusercontent.com/675615/75873286-f5d32f80-5e0f-11ea-950e-fd9691137f7c.png)

It can be used like this:
https://github.com/pmedianetwork/eslint-config/blob/sensible-imports/index.js#L31

Issues are reported as warnings for now. Here is how they are reported:
https://ci.adverity.net/blue/rest/organizations/jenkins/pipelines/PRESENSE-PR-FRONTEND-CHECKS/runs/1160/nodes/39/log/?start=0

And in IDE looks like this
![image](https://user-images.githubusercontent.com/675615/75873723-b5c07c80-5e10-11ea-8dae-6b18570a2397.png)

**BUT:**
I am having an issue getting it perfectly right. 
Currently it makes a bold assumption that the codebase is in one folder down relative to the project root (for example `/src`) which might not be true for each project.
I need this check to cover some of the edge cases. 

It will work for presence, but I still need to test it with other projects.

---

@TkDodo commented on [Wed Mar 04 2020](https://github.com/pmedianetwork/adverity-presense-frontend/issues/327#issuecomment-594468188)

🎉 

---

@adamgajzlerowicz commented on [Thu Mar 05 2020](https://github.com/pmedianetwork/adverity-presense-frontend/issues/327#issuecomment-595094533)

I asked a question on eslint gitter channel. It is not possible to have rules in config. 

![image.png](https://images.zenhubusercontent.com/5c51dc23937b4373eb7a477d/3eb2a038-0958-47e4-a56b-607926353d03)

@TkDodo Suggested importing a rule locally, but that will work only locally [article](https://medium.com/neighborhoods-com-engineering-blog/custom-eslint-rules-for-faster-refactoring-2095e69bde08)

There is a way to do this in one repository. We need to change this repositories shape to become a plugin (instead of config)

This is explained [here](https://eslint.org/docs/developer-guide/working-with-plugins#configs-in-plugins)

**Comment by TkDodo** [comment]
> There is a way to do this in one repository. We need to change this repositories shape to become a plugin (instead of config)

I didn't read it, but if it works, it would definitely be preferred to multiple repos.
